/**
 * Generated by scripts/build-demo-fixture.ts. Do not hand-edit — rerun the
 * script instead. The one result this portfolio deploy ever shows.
 */
import type { MenuResponse } from '@/lib/types';

export const DEMO_MENU_RESPONSE: MenuResponse = {
  "url": "https://example.com/menu",
  "source": "scrape",
  "seed": 215906937,
  "restaurantName": "Le Bon Coin (example restaurant)",
  "dishes": [
    {
      "name": "Soupe à l'Oignon",
      "price": "$14",
      "priceValue": 14,
      "description": "Gratinéed with comté, baked overnight.",
      "category": "Starters"
    },
    {
      "name": "Escargots",
      "price": "$16",
      "priceValue": 16,
      "description": "six, in garlic butter, as they should be",
      "category": "Starters"
    },
    {
      "name": "Caesar Salad",
      "price": "$15",
      "priceValue": 15,
      "category": "Starters"
    },
    {
      "name": "Steak Frites",
      "price": "$34",
      "priceValue": 34,
      "description": "Bavette, maître d'hôtel butter, hand-cut fries",
      "category": "Mains"
    },
    {
      "name": "Duck Confit",
      "price": "$31",
      "priceValue": 31,
      "description": "Braised lentils, garlic sausage",
      "category": "Mains"
    },
    {
      "name": "Coq au Vin",
      "price": "$29",
      "priceValue": 29,
      "description": "Red wine, pearl onions, lardons",
      "category": "Mains"
    },
    {
      "name": "Sole Meunière",
      "price": "$38",
      "priceValue": 38,
      "description": "Brown butter, capers, lemon",
      "category": "Mains"
    },
    {
      "name": "Ratatouille",
      "price": "$24",
      "priceValue": 24,
      "description": "Summer vegetables, basil oil",
      "category": "Mains"
    },
    {
      "name": "Cassoulet",
      "price": "$33",
      "priceValue": 33,
      "description": "Toulouse sausage, duck, white beans. For two, ideally.",
      "category": "Mains"
    },
    {
      "name": "Steak Tartare",
      "price": "$27",
      "priceValue": 27,
      "description": "hand-cut, capers, cornichon, egg yolk",
      "category": "Mains"
    },
    {
      "name": "Tarte Tatin",
      "price": "$12",
      "priceValue": 12,
      "description": "Caramelised apple, crème fraîche.",
      "category": "Desserts"
    }
  ],
  "partySize": 4,
  "picks": [
    {
      "dish": {
        "name": "Escargots",
        "price": "$16",
        "priceValue": 16,
        "description": "six, in garlic butter, as they should be",
        "category": "Starters"
      },
      "course": "starter",
      "shared": true,
      "justification": "The matter has been settled. You are having the Escargots. A meal without a first move is merely eating. Corroboration is extensive: 8 separate accounts. The file notes six without further comment. At $16 the cost is neither a concession nor an extravagance. With a party of 4, this is where the distribution settles. The conclusion has been checked and it holds."
    },
    {
      "dish": {
        "name": "Soupe à l'Oignon",
        "price": "$14",
        "priceValue": 14,
        "description": "Gratinéed with comté, baked overnight.",
        "category": "Starters"
      },
      "course": "starter",
      "shared": true,
      "justification": "The finding was reached without dissent. You are having the Soupe à l'Oignon. It sets expectations at the correct level. Gratinéed with comté survived review without amendment. At $14 the outlay is modest and easily justified. Scaled to 4, the order holds its shape. Objections may be filed, but they will not prevail."
    },
    {
      "dish": {
        "name": "Sole Meunière",
        "price": "$38",
        "priceValue": 38,
        "description": "Brown butter, capers, lemon",
        "category": "Mains"
      },
      "course": "main",
      "seat": 1,
      "shared": false,
      "justification": "Following review, the outcome is not in question. You are having the Sole Meunière. It answers the question the meal was asking. The record contains 12 corroborating accounts. The presence of capers has been noted and accepted. At $38 the figure reflects the seriousness of the choice. With a party of 4, this is where the distribution settles. Later review is not anticipated to disturb this."
    },
    {
      "dish": {
        "name": "Duck Confit",
        "price": "$31",
        "priceValue": 31,
        "description": "Braised lentils, garlic sausage",
        "category": "Mains"
      },
      "course": "main",
      "seat": 2,
      "shared": false,
      "justification": "Let the record show the decision was unanimous. You are having the Duck Confit. It occupies the principal seat without difficulty. This is the most heavily corroborated item in the file. The inclusion of garlic sausage was considered and raised no objection. At $31 the outlay is significant and entirely intentional. For a table of 4, the arithmetic supports no other arrangement. Later review is not anticipated to disturb this."
    },
    {
      "dish": {
        "name": "Cassoulet",
        "price": "$33",
        "priceValue": 33,
        "description": "Toulouse sausage, duck, white beans. For two, ideally.",
        "category": "Mains"
      },
      "course": "main",
      "seat": 3,
      "shared": false,
      "justification": "Let the record show the decision was unanimous. You are having the Cassoulet. It was selected to bear the weight of the meal, and it does. There is corroboration, and it is favourable. Toulouse sausage formed part of the accepted specification. At $33 the expenditure has been authorised in full. With 4 at the table, the order balances precisely here. Later review is not anticipated to disturb this."
    },
    {
      "dish": {
        "name": "Coq au Vin",
        "price": "$29",
        "priceValue": 29,
        "description": "Red wine, pearl onions, lardons",
        "category": "Mains"
      },
      "course": "main",
      "seat": 4,
      "shared": false,
      "justification": "The finding was reached without dissent. You are having the Coq au Vin. The remainder of the order arranges itself around it. Red wine, as described, raised no objection. At $29 it is priced in line with its function. The seating of 4 was taken into account and changes nothing. Nothing in the record contradicts it."
    },
    {
      "dish": {
        "name": "Tarte Tatin",
        "price": "$12",
        "priceValue": 12,
        "description": "Caramelised apple, crème fraîche.",
        "category": "Desserts"
      },
      "course": "dessert",
      "shared": true,
      "justification": "This was never seriously in doubt. You are having the Tarte Tatin. It is the correct final entry. 15 independent accounts corroborate this. Caramelised apple: noted, and accepted. At $12 it represents a straightforward use of the budget. The seating of 4 was taken into account and changes nothing. Nothing in the record contradicts it."
    }
  ],
  "signals": {
    "Duck Confit": {
      "mentions": 47,
      "score": 41
    },
    "Steak Frites": {
      "mentions": 31,
      "score": 0
    },
    "Sole Meunière": {
      "mentions": 12,
      "score": 9
    },
    "Escargots": {
      "mentions": 8,
      "score": 6
    },
    "Tarte Tatin": {
      "mentions": 15,
      "score": 14
    },
    "Cassoulet": {
      "mentions": 1,
      "score": 1
    },
    "Ratatouille": {
      "mentions": 9,
      "score": -7
    },
    "Caesar Salad": {
      "mentions": 4,
      "score": -2
    },
    "Crème Brûlée": {
      "mentions": 3,
      "score": 0
    }
  },
  "facts": {
    "Soupe à l'Oignon": {
      "name": "Soupe à l'Oignon",
      "description": "French onion soup is a soup of onions which are sautéed and then cooked in meat stock or water, usually served gratinéed with croutons or a larger piece of bread covered with cheese floating on top.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Soupe_%C3%A0_l%27oignon.jpg/960px-Soupe_%C3%A0_l%27oignon.jpg",
      "ingredients": [
        "onion",
        "beef stock",
        "gruyère cheese",
        "baguette",
        "butter",
        "thyme"
      ],
      "searchUrl": "https://www.google.com/search?q=Soupe%20%C3%A0%20l'Oignon%20dish",
      "source": "wikipedia"
    },
    "Escargots": {
      "name": "Escargots",
      "description": "Snails are eaten by humans in many areas such as Africa, Southeast Asia and Mediterranean Europe, while in other cultures, snails are seen as a taboo food.",
      "photoUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Caracoles-del-restaurante-granero.jpg",
      "ingredients": [
        "snails",
        "garlic",
        "butter",
        "parsley"
      ],
      "searchUrl": "https://www.google.com/search?q=Escargots%20dish",
      "source": "wikipedia"
    },
    "Caesar Salad": {
      "name": "Caesar Salad",
      "description": "A Caesar salad, also known as Caesar's salad, is a green salad of romaine lettuce and croutons commonly dressed with lemon juice, olive oil, eggs, Worcestershire sauce, anchovies, garlic, Dijon mustard, Parmesan and black pepper.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Caesar_salad_%282%29.jpg/960px-Caesar_salad_%282%29.jpg",
      "ingredients": [
        "romaine lettuce",
        "croutons",
        "parmesan",
        "anchovy",
        "garlic",
        "lemon juice",
        "egg"
      ],
      "searchUrl": "https://www.google.com/search?q=Caesar%20Salad%20dish",
      "source": "wikipedia"
    },
    "Steak Frites": {
      "name": "Steak Frites",
      "description": "Steak frites, meaning \"steak [and] chipped potatoes\" in French, is a dish consisting of beefsteak accompanied by fried chipped potatoes.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Reel_and_Brand_-_September_2021_-_Sarah_Stierch_05.jpg/960px-Reel_and_Brand_-_September_2021_-_Sarah_Stierch_05.jpg",
      "ingredients": [
        "beef steak",
        "potato",
        "butter",
        "parsley"
      ],
      "searchUrl": "https://www.google.com/search?q=Steak%20Frites%20dish",
      "source": "wikipedia"
    },
    "Duck Confit": {
      "name": "Duck Confit",
      "description": "Duck confit is a French dish made with whole duck.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Confitdecanard.jpg/960px-Confitdecanard.jpg",
      "ingredients": [
        "duck leg",
        "garlic",
        "thyme",
        "duck fat",
        "salt"
      ],
      "searchUrl": "https://www.google.com/search?q=Duck%20Confit%20dish",
      "source": "wikipedia"
    },
    "Coq au Vin": {
      "name": "Coq au Vin",
      "description": "Coq au vin is a French dish of chicken braised with wine, lardons, mushrooms, and optionally garlic.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Gourmet_coq_au_vin.jpg/960px-Gourmet_coq_au_vin.jpg",
      "ingredients": [
        "chicken",
        "red wine",
        "bacon",
        "mushroom",
        "pearl onion",
        "garlic"
      ],
      "searchUrl": "https://www.google.com/search?q=Coq%20au%20Vin%20dish",
      "source": "wikipedia"
    },
    "Sole Meunière": {
      "name": "Sole Meunière",
      "description": "Sole meunière is a classic French fish dish consisting of sole – floured and fried – and served with hot melted butter, lemon juice, and parsley.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Sole_meuniere_%284689490702%29.jpg/960px-Sole_meuniere_%284689490702%29.jpg",
      "ingredients": [
        "sole",
        "butter",
        "lemon",
        "parsley",
        "flour"
      ],
      "searchUrl": "https://www.google.com/search?q=Sole%20Meuni%C3%A8re%20dish",
      "source": "wikipedia"
    },
    "Ratatouille": {
      "name": "Ratatouille",
      "description": "Ratatouille is a traditional French vegetable dish originating in the Provence region of southern France, particularly associated with Nice and its surrounding region.",
      "photoUrl": "https://upload.wikimedia.org/wikipedia/commons/3/37/Ratatouille_home_cooked.jpg",
      "ingredients": [
        "eggplant",
        "zucchini",
        "bell pepper",
        "tomato",
        "onion",
        "garlic",
        "basil"
      ],
      "searchUrl": "https://www.google.com/search?q=Ratatouille%20dish",
      "source": "wikipedia"
    },
    "Cassoulet": {
      "name": "Cassoulet",
      "description": "Cassoulet is a rich stew originating in southern France.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Bowl_of_cassoulet.JPG/960px-Bowl_of_cassoulet.JPG",
      "ingredients": [
        "white bean",
        "duck",
        "pork sausage",
        "bacon",
        "garlic",
        "onion"
      ],
      "searchUrl": "https://www.google.com/search?q=Cassoulet%20dish",
      "source": "wikipedia"
    },
    "Steak Tartare": {
      "name": "Steak Tartare",
      "description": "Steak tartare, or tartar steak, is a French dish of raw ground (minced) beef.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Classic_steak_tartare.jpg/960px-Classic_steak_tartare.jpg",
      "ingredients": [
        "beef",
        "egg yolk",
        "caper",
        "onion",
        "cornichon",
        "mustard"
      ],
      "searchUrl": "https://www.google.com/search?q=Steak%20Tartare%20dish",
      "source": "wikipedia"
    },
    "Tarte Tatin": {
      "name": "Tarte Tatin",
      "description": "The tarte Tatin is a tart in which the fruit is caramelized in butter and sugar before the tart is baked.",
      "photoUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Franse_tarte_tatin.jpg/960px-Franse_tarte_tatin.jpg",
      "ingredients": [
        "apple",
        "butter",
        "sugar",
        "puff pastry"
      ],
      "searchUrl": "https://www.google.com/search?q=Tarte%20Tatin%20dish",
      "source": "wikipedia"
    }
  }
};
