/**
 * Generates lib/fixtures/demo-response.ts: one precomputed MenuResponse, built
 * from the same pure pipeline /api/menu used (spin + justify) over the sample
 * menu. The portfolio deploy has no API routes, so it renders this fixture
 * directly instead of fetching anything. Rerun after editing sample data.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SAMPLE_DISHES, SAMPLE_FACTS } from '../lib/fixtures';
import { SAMPLE_SIGNALS } from '../lib/fixtures/sample-signals';
import { hashSeed, seededRng, spin } from '../lib/roulette';
import { justify } from '../lib/justify';
import type { Dish, DishFacts, MenuResponse } from '../lib/types';

const PARTY_SIZE = 4;
const SEED = hashSeed('dishly-portfolio-demo');

function searchUrl(name: string): string {
  return `https://www.google.com/search?q=${encodeURIComponent(`${name} dish`)}`;
}

function factsFor(dish: Dish): DishFacts {
  return (
    SAMPLE_FACTS[dish.name] ?? {
      name: dish.name,
      description: dish.description,
      searchUrl: searchUrl(dish.name),
      source: dish.description ? 'menu' : 'none',
    }
  );
}

/** classifyAll tags the pool's dishes with `course` in place — strip it back off before it leaks into the fixture as a stray Dish field. */
function plainDish(dish: Dish): Dish {
  const { name, price, priceValue, description, category } = dish;
  return { name, price, priceValue, description, category };
}

const rng = seededRng(SEED);
const picks = spin(SAMPLE_DISHES, PARTY_SIZE, rng, SAMPLE_SIGNALS).map((p) => ({
  ...p,
  dish: plainDish(p.dish),
  justification: justify(p.dish, p.course, PARTY_SIZE, SAMPLE_SIGNALS[p.dish.name]),
}));

const facts: Record<string, DishFacts> = {};
for (const dish of SAMPLE_DISHES) facts[dish.name] = factsFor(dish);

const response: MenuResponse = {
  url: 'https://example.com/menu',
  source: 'scrape',
  seed: SEED,
  restaurantName: 'Le Bon Coin (example restaurant)',
  dishes: SAMPLE_DISHES,
  partySize: PARTY_SIZE,
  picks,
  signals: SAMPLE_SIGNALS,
  facts,
};

const out = `/**
 * Generated by scripts/build-demo-fixture.ts. Do not hand-edit — rerun the
 * script instead. The one result this portfolio deploy ever shows.
 */
import type { MenuResponse } from '@/lib/types';

export const DEMO_MENU_RESPONSE: MenuResponse = ${JSON.stringify(response, null, 2)};
`;

writeFileSync(join(process.cwd(), 'lib/fixtures/demo-response.ts'), out, 'utf8');
console.log('Wrote lib/fixtures/demo-response.ts');
